### Get all users
GET {{host}}/users
Content-Type: application/json

### Get users by filters
GET {{host}}/users?id="7"
Content-Type: application/json

### Get me
GET {{host}}/users/me
Content-Type: application/json

### Create user
POST {{host}}/users
Content-Type: application/json

{
  "role": 1,
  "first_name": "Test",
  "last_name": "Test",
  "email": "test@mail.ru",
  "password": "111"
}



### Update user
PUT {{host}}/user
Content-Type: application/json

{
  "id": 9,
  "first_name": "Pop",
  "last_name": "Pop",
  "organization": 1,
  "position": 2,
  "email": "pop@mail.ru",
  "password": "123"
}

### Delete user by ID
DELETE {{host}}/user/10
Content-Type: application/json

### User auth
POST {{host}}/login
Content-Type: application/json

{
  "email": "helen@mail.ru",
  "password": "helen11"
}