### User authz
POST {{host}}/login
Content-Type: application/json

{
  "email": "ivan",
  "password": "123"
}

### Get users
GET {{host}}/users?email=sergey.sokolov@example.com&email=elena.popova@example.com
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjkxOTE3NzUsImlkIjoxfQ.LXnU6hiPgZuPFtllLHKWrMYesXnSoFbVHA9yIGmYx1s

### Get me
GET {{host}}/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE0NTEyNzcsImlkIjoxfQ.i90LHxLRmBTOeZ7AaZ_XdTy2SJsfe70eVkYR8YOjob4

### Create user
POST {{host}}/sign_up
Content-Type: application/json

{
  "role": "Employee",
  "first_name": "Test",
  "last_name": "Test",
  "email": "test3@mail.ru",
  "password": "111"
}

### Update user
PUT {{host}}/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwMTYyMDYsImlkIjoyMX0.s5FEKJp2fqwWwS6b0OKXXZq6_W2hDfIuwd6pclD_j-o

{
  "first_name": "Test",
  "last_name": "Test",
  "email": "test@mail.ru",
  "password": "111"
}

### Attach user
PUT {{host}}/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwMTAzNjYsImlkIjoyM30.q6rwspvkkHY7j4hMmZ8gdKeOSS1ZfN7Bjblrb1U8f-o

{
  "id": 23,
  "organization_id": 1,
  "position_id": 1
}

### Get all organizations
GET {{host}}/organizations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwMTgyODEsImlkIjoyMX0.Y2NUHGTt3Q1r1bE3paacHRADxYMFywkZiXieeXBvnuU

### Get all positions
GET {{host}}/positions?id=3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA3MzgyNzEsImlkIjoxfQ.kuKkY2XleQsDv1dZ_td9dTq7cW31yR37chVwcH9nTmE

### Create position
POST {{host}}/positions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwMjI2NjUsImlkIjoyMX0.QZFtIVpNfq4djGdUwMMvBXrB6va_qRlsIZmK1C7xilI

{
  "name": "Test"
}

### Update position
PUT {{host}}/positions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwMjI2NjUsImlkIjoyMX0.QZFtIVpNfq4djGdUwMMvBXrB6va_qRlsIZmK1C7xilI

{
  "id": 2,
  "name": "Intern"
}