environment: dev

server:
  address: localhost
  port: 8000
  secret_key: a79c73a0-9ca5-4a16-afef-296497aff250
  token_exp_time: 15

db:
  host: 45.153.230.86
  port: 5432
  user_name: bee
  password: OZ15Hv1qVj2E
  dbname: store